import { EnrollmentInput } from '../db/models/Enrollment';
import { StudentInput } from '../db/models/Student';
import { StudyGroupInput } from '../db/models/StudyGroup';

export const students: StudentInput[] = [
  {
    name: 'Zane Maxwell',
    sex: 'Male',
    email: 'zmaxwell0@mapquest.com',
    placeOfBirth: '40876 Hallows Place',
    dateOfBirth: new Date('1980-03-29'),
  },
  {
    name: 'Rockwell De Ambrosi',
    sex: 'Male',
    email: 'rde1@e-recht24.de',
    placeOfBirth: '1809 Warrior Park',
    dateOfBirth: new Date('2014-12-15'),
  },
  {
    name: 'Dorthy Blacklidge',
    sex: 'Female',
    email: 'dblacklidge2@tinyurl.com',
    placeOfBirth: '04543 Haas Junction',
    dateOfBirth: new Date('2007-05-29'),
  },
  {
    name: 'Susi Lawrie',
    sex: 'Male',
    email: 'slawrie3@sourceforge.net',
    placeOfBirth: '9088 Victoria Hill',
    dateOfBirth: new Date('1996-01-10'),
  },
  {
    name: 'Loise Bendig',
    sex: 'Female',
    email: 'lbendig4@drupal.org',
    placeOfBirth: '6 Myrtle Place',
    dateOfBirth: new Date('1967-08-25'),
  },
  {
    name: 'Dannel Skalls',
    sex: 'Female',
    email: 'dskalls5@go.com',
    placeOfBirth: '3198 Donald Circle',
    dateOfBirth: new Date('1950-09-29'),
  },
  {
    name: 'Suki Chotty',
    sex: 'Female',
    email: 'schotty6@feedburner.com',
    placeOfBirth: '291 Bluejay Trail',
    dateOfBirth: new Date('1991-03-07'),
  },
  {
    name: 'Helene Banting',
    sex: 'Female',
    email: 'hbanting7@de.vu',
    placeOfBirth: '59 School Terrace',
    dateOfBirth: new Date('1965-12-21'),
  },
  {
    name: 'Cameron Knox',
    sex: 'Male',
    email: 'cknox8@nydailynews.com',
    placeOfBirth: '93116 Roth Plaza',
    dateOfBirth: new Date('1983-01-10'),
  },
  {
    name: 'Brian Canape',
    sex: 'Male',
    email: 'bcanape9@biglobe.ne.jp',
    placeOfBirth: '8179 Judy Way',
    dateOfBirth: new Date('1984-10-04'),
  },
  {
    name: 'Stan Howley',
    sex: 'Male',
    email: 'showleya@paypal.com',
    placeOfBirth: '072 Meadow Valley Pass',
    dateOfBirth: new Date('2009-10-02'),
  },
  {
    name: 'Maggy Derham',
    sex: 'Female',
    email: 'mderhamb@tuttocitta.it',
    placeOfBirth: '288 Bartelt Parkway',
    dateOfBirth: new Date('1992-08-01'),
  },
  {
    name: 'Maggee Tuttle',
    sex: 'Female',
    email: 'mtuttlec@cocolog-nifty.com',
    placeOfBirth: '17674 Quincy Center',
    dateOfBirth: new Date('1996-03-10'),
  },
  {
    name: 'Dreddy Chessor',
    sex: 'Female',
    email: 'dchessord@webeden.co.uk',
    placeOfBirth: '524 Larry Circle',
    dateOfBirth: new Date('1983-04-16'),
  },
  {
    name: 'Nicole Yapp',
    sex: 'Female',
    email: 'nyappe@mysql.com',
    placeOfBirth: '67194 Namekagon Trail',
    dateOfBirth: new Date('1968-07-21'),
  },
  {
    name: 'Esteban Andrieux',
    sex: 'Male',
    email: 'eandrieuxf@cdc.gov',
    placeOfBirth: '8 Burrows Court',
    dateOfBirth: new Date('2012-11-26'),
  },
  {
    name: 'Clemmie Ayton',
    sex: 'Female',
    email: 'caytong@prweb.com',
    placeOfBirth: '160 Ohio Trail',
    dateOfBirth: new Date('1971-05-08'),
  },
  {
    name: 'Doretta Dunrige',
    sex: 'Female',
    email: 'ddunrigeh@netlog.com',
    placeOfBirth: '479 Lindbergh Junction',
    dateOfBirth: new Date('1953-06-04'),
  },
  {
    name: 'Isabelita Ply',
    sex: 'Female',
    email: 'iplyi@instagram.com',
    placeOfBirth: '834 Ridgeview Drive',
    dateOfBirth: new Date('1951-03-10'),
  },
  {
    name: 'Markos Orlton',
    sex: 'Male',
    email: 'morltonj@joomla.org',
    placeOfBirth: '110 Londonderry Point',
    dateOfBirth: new Date('1995-02-16'),
  },
  {
    name: 'Quintana Lacrouts',
    sex: 'Female',
    email: 'qlacroutsk@smh.com.au',
    placeOfBirth: '8 Parkside Road',
    dateOfBirth: new Date('2015-07-21'),
  },
  {
    name: 'Rabbi Quipp',
    sex: 'Male',
    email: 'rquippl@jigsy.com',
    placeOfBirth: '6030 Eagle Crest Road',
    dateOfBirth: new Date('1997-06-02'),
  },
  {
    name: 'Eleen Cornau',
    sex: 'Female',
    email: 'ecornaum@deliciousdays.com',
    placeOfBirth: '79903 Fairview Place',
    dateOfBirth: new Date('1988-08-13'),
  },
  {
    name: 'Terri-jo Newcom',
    sex: 'Female',
    email: 'tnewcomn@flickr.com',
    placeOfBirth: '81 Lukken Trail',
    dateOfBirth: new Date('1989-06-25'),
  },
  {
    name: 'Nathanial Garland',
    sex: 'Male',
    email: 'ngarlando@ebay.co.uk',
    placeOfBirth: '116 Melody Drive',
    dateOfBirth: new Date('2000-01-23'),
  },
  {
    name: 'Teddie Sprigin',
    sex: 'Female',
    email: 'tspriginp@telegraph.co.uk',
    placeOfBirth: '726 Old Gate Trail',
    dateOfBirth: new Date('2002-03-27'),
  },
  {
    name: 'Michele Cosstick',
    sex: 'Female',
    email: 'mcosstickq@boston.com',
    placeOfBirth: '496 Truax Park',
    dateOfBirth: new Date('2001-06-20'),
  },
  {
    name: 'Marcus Manklow',
    sex: 'Male',
    email: 'mmanklowr@tripadvisor.com',
    placeOfBirth: '7454 Commercial Center',
    dateOfBirth: new Date('2009-12-06'),
  },
  {
    name: 'Con Messitt',
    sex: 'Male',
    email: 'cmessitts@naver.com',
    placeOfBirth: '9501 Doe Crossing Avenue',
    dateOfBirth: new Date('1988-11-05'),
  },
  {
    name: 'Sergeant Rozenbaum',
    sex: 'Male',
    email: 'srozenbaumt@bing.com',
    placeOfBirth: '1935 Hayes Drive',
    dateOfBirth: new Date('2001-10-28'),
  },
  {
    name: 'Bennett Martinelli',
    sex: 'Male',
    email: 'bmartinelliu@wordpress.com',
    placeOfBirth: '11 Bellgrove Parkway',
    dateOfBirth: new Date('1978-08-04'),
  },
  {
    name: 'Judas Cullum',
    sex: 'Female',
    email: 'jcullumv@ucla.edu',
    placeOfBirth: '673 Holy Cross Alley',
    dateOfBirth: new Date('2014-05-22'),
  },
  {
    name: 'Kristos Twinbourne',
    sex: 'Male',
    email: 'ktwinbournew@eventbrite.com',
    placeOfBirth: '72 Hazelcrest Point',
    dateOfBirth: new Date('2000-05-13'),
  },
  {
    name: 'Gussi Kraut',
    sex: 'Female',
    email: 'gkrautx@webmd.com',
    placeOfBirth: '068 Morrow Street',
    dateOfBirth: new Date('1969-03-14'),
  },
  {
    name: 'Dayna Boothroyd',
    sex: 'Female',
    email: 'dboothroydy@privacy.gov.au',
    placeOfBirth: '32896 Sutteridge Parkway',
    dateOfBirth: new Date('1979-03-26'),
  },
  {
    name: 'Arlan Dollar',
    sex: 'Male',
    email: 'adollarz@tinyurl.com',
    placeOfBirth: '847 Basil Point',
    dateOfBirth: new Date('2007-11-30'),
  },
  {
    name: 'Adoree MacConnel',
    sex: 'Female',
    email: 'amacconnel10@icio.us',
    placeOfBirth: '4066 Continental Plaza',
    dateOfBirth: new Date('1996-03-03'),
  },
  {
    name: 'Godwin Syme',
    sex: 'Male',
    email: 'gsyme11@accuweather.com',
    placeOfBirth: '80 South Crossing',
    dateOfBirth: new Date('2015-09-29'),
  },
  {
    name: 'Rustin Daouse',
    sex: 'Male',
    email: 'rdaouse12@cloudflare.com',
    placeOfBirth: '8 Sundown Drive',
    dateOfBirth: new Date('2009-09-10'),
  },
  {
    name: 'Bentley Hawkeswood',
    sex: 'Male',
    email: 'bhawkeswood13@istockphoto.com',
    placeOfBirth: '189 Melvin Point',
    dateOfBirth: new Date('1979-02-14'),
  },
  {
    name: 'Renelle Wedgwood',
    sex: 'Female',
    email: 'rwedgwood14@google.es',
    placeOfBirth: '1 Bay Junction',
    dateOfBirth: new Date('1973-03-23'),
  },
  {
    name: 'Federico Knaggs',
    sex: 'Male',
    email: 'fknaggs15@wufoo.com',
    placeOfBirth: '11 Forster Street',
    dateOfBirth: new Date('1955-01-15'),
  },
  {
    name: 'Tandy Bazek',
    sex: 'Female',
    email: 'tbazek16@skyrock.com',
    placeOfBirth: '82 Old Shore Circle',
    dateOfBirth: new Date('1960-07-19'),
  },
  {
    name: 'Mandy Brien',
    sex: 'Female',
    email: 'mbrien17@rambler.ru',
    placeOfBirth: '06 Monterey Point',
    dateOfBirth: new Date('1956-12-28'),
  },
  {
    name: 'Wye Bretton',
    sex: 'Male',
    email: 'wbretton18@wikipedia.org',
    placeOfBirth: '120 Sunfield Junction',
    dateOfBirth: new Date('2020-04-19'),
  },
  {
    name: 'Jenine Sorton',
    sex: 'Female',
    email: 'jsorton19@xrea.com',
    placeOfBirth: '40 Eagan Lane',
    dateOfBirth: new Date('1998-05-25'),
  },
  {
    name: 'Costanza Chadwyck',
    sex: 'Female',
    email: 'cchadwyck1a@networksolutions.com',
    placeOfBirth: '9 Oak Alley',
    dateOfBirth: new Date('2007-10-27'),
  },
  {
    name: 'Reid Nicholas',
    sex: 'Male',
    email: 'rnicholas1b@elegantthemes.com',
    placeOfBirth: '812 Jana Parkway',
    dateOfBirth: new Date('2011-04-23'),
  },
  {
    name: 'Chip Jatczak',
    sex: 'Male',
    email: 'cjatczak1c@quantcast.com',
    placeOfBirth: '10491 Ruskin Avenue',
    dateOfBirth: new Date('1967-10-01'),
  },
  {
    name: 'Cesare Messier',
    sex: 'Male',
    email: 'cmessier1d@narod.ru',
    placeOfBirth: '21881 Graceland Point',
    dateOfBirth: new Date('1964-09-30'),
  },
  {
    name: 'Elka Petzold',
    sex: 'Female',
    email: 'epetzold1e@mediafire.com',
    placeOfBirth: '9222 Di Loreto Court',
    dateOfBirth: new Date('2013-04-21'),
  },
  {
    name: 'Avictor Domleo',
    sex: 'Male',
    email: 'adomleo1f@disqus.com',
    placeOfBirth: '778 Golf Avenue',
    dateOfBirth: new Date('1965-07-09'),
  },
  {
    name: 'Rawley Vyel',
    sex: 'Male',
    email: 'rvyel1g@cam.ac.uk',
    placeOfBirth: '761 Montana Street',
    dateOfBirth: new Date('1972-01-05'),
  },
  {
    name: 'Sallyanne Zannolli',
    sex: 'Female',
    email: 'szannolli1h@goodreads.com',
    placeOfBirth: '6 Canary Park',
    dateOfBirth: new Date('2021-03-28'),
  },
  {
    name: 'Ciro Chorley',
    sex: 'Male',
    email: 'cchorley1i@abc.net.au',
    placeOfBirth: '218 Fieldstone Avenue',
    dateOfBirth: new Date('1989-05-15'),
  },
  {
    name: 'Raychel Waples',
    sex: 'Female',
    email: 'rwaples1j@g.co',
    placeOfBirth: '1789 Brickson Park Point',
    dateOfBirth: new Date('1965-07-30'),
  },
  {
    name: 'Raymond Kilgrove',
    sex: 'Male',
    email: 'rkilgrove1k@sina.com.cn',
    placeOfBirth: '1267 Mifflin Street',
    dateOfBirth: new Date('2016-08-03'),
  },
  {
    name: 'Olivie Dealtry',
    sex: 'Female',
    email: 'odealtry1l@myspace.com',
    placeOfBirth: '0302 Mallard Pass',
    dateOfBirth: new Date('1973-09-11'),
  },
  {
    name: 'Wit Mersh',
    sex: 'Male',
    email: 'wmersh1m@macromedia.com',
    placeOfBirth: '857 Service Trail',
    dateOfBirth: new Date('1986-04-27'),
  },
  {
    name: 'Noby Witherspoon',
    sex: 'Male',
    email: 'nwitherspoon1n@cargocollective.com',
    placeOfBirth: '40238 Arapahoe Street',
    dateOfBirth: new Date('1963-04-14'),
  },
  {
    name: 'Guendolen Basham',
    sex: 'Female',
    email: 'gbasham1o@google.fr',
    placeOfBirth: '04370 Bayside Way',
    dateOfBirth: new Date('2016-03-20'),
  },
  {
    name: 'Farris Grishkov',
    sex: 'Male',
    email: 'fgrishkov1p@topsy.com',
    placeOfBirth: '052 Stoughton Circle',
    dateOfBirth: new Date('1990-06-30'),
  },
  {
    name: 'Fayette Jaszczak',
    sex: 'Female',
    email: 'fjaszczak1q@addthis.com',
    placeOfBirth: '59153 East Lane',
    dateOfBirth: new Date('2012-03-07'),
  },
  {
    name: 'Deena Alltimes',
    sex: 'Female',
    email: 'dalltimes1r@moonfruit.com',
    placeOfBirth: '24 Sachs Pass',
    dateOfBirth: new Date('2017-10-26'),
  },
  {
    name: 'Bee Shackell',
    sex: 'Female',
    email: 'bshackell1s@ftc.gov',
    placeOfBirth: '8 Elka Street',
    dateOfBirth: new Date('1980-04-16'),
  },
  {
    name: 'Francisco Satterthwaite',
    sex: 'Male',
    email: 'fsatterthwaite1t@examiner.com',
    placeOfBirth: '8 Di Loreto Plaza',
    dateOfBirth: new Date('1979-09-14'),
  },
  {
    name: 'Virge Gages',
    sex: 'Male',
    email: 'vgages1u@unc.edu',
    placeOfBirth: '02 Blue Bill Park Crossing',
    dateOfBirth: new Date('1993-02-17'),
  },
  {
    name: 'Jamey Teacy',
    sex: 'Male',
    email: 'jteacy1v@theatlantic.com',
    placeOfBirth: '6489 Straubel Street',
    dateOfBirth: new Date('2010-09-25'),
  },
  {
    name: 'Jaymie Wrotchford',
    sex: 'Male',
    email: 'jwrotchford1w@wiley.com',
    placeOfBirth: '1505 Mayfield Crossing',
    dateOfBirth: new Date('1995-11-17'),
  },
  {
    name: 'Lavena Zorzenoni',
    sex: 'Female',
    email: 'lzorzenoni1x@youtube.com',
    placeOfBirth: '2 Sunfield Pass',
    dateOfBirth: new Date('1980-10-08'),
  },
  {
    name: 'Siana De la croix',
    sex: 'Male',
    email: 'sde1y@boston.com',
    placeOfBirth: '03308 Randy Alley',
    dateOfBirth: new Date('2013-02-08'),
  },
  {
    name: 'Jacquelynn Holwell',
    sex: 'Female',
    email: 'jholwell1z@irs.gov',
    placeOfBirth: '36 Dottie Point',
    dateOfBirth: new Date('1988-10-05'),
  },
  {
    name: 'Tootsie Sentinella',
    sex: 'Female',
    email: 'tsentinella20@theglobeandmail.com',
    placeOfBirth: '15 Paget Street',
    dateOfBirth: new Date('1991-04-16'),
  },
  {
    name: 'Bradney Kissick',
    sex: 'Male',
    email: 'bkissick21@smugmug.com',
    placeOfBirth: '18976 Maple Pass',
    dateOfBirth: new Date('1979-01-05'),
  },
  {
    name: 'Caryn Hagan',
    sex: 'Male',
    email: 'chagan22@blogger.com',
    placeOfBirth: '64 Waxwing Hill',
    dateOfBirth: new Date('1988-01-31'),
  },
  {
    name: 'Cornelia Garham',
    sex: 'Female',
    email: 'cgarham23@xinhuanet.com',
    placeOfBirth: '33 Schlimgen Terrace',
    dateOfBirth: new Date('2018-09-22'),
  },
  {
    name: 'Jessa Bestwall',
    sex: 'Female',
    email: 'jbestwall24@booking.com',
    placeOfBirth: '75 Service Plaza',
    dateOfBirth: new Date('2015-09-20'),
  },
  {
    name: 'Tracee Hatt',
    sex: 'Female',
    email: 'thatt25@china.com.cn',
    placeOfBirth: '11 Brown Alley',
    dateOfBirth: new Date('1978-01-14'),
  },
  {
    name: 'Waly Mesnard',
    sex: 'Female',
    email: 'wmesnard26@springer.com',
    placeOfBirth: '26 Everett Crossing',
    dateOfBirth: new Date('1966-10-09'),
  },
  {
    name: 'Elli Derisley',
    sex: 'Female',
    email: 'ederisley27@list-manage.com',
    placeOfBirth: '88299 Charing Cross Park',
    dateOfBirth: new Date('1979-09-06'),
  },
  {
    name: 'Jania Drewson',
    sex: 'Female',
    email: 'jdrewson28@miibeian.gov.cn',
    placeOfBirth: '9439 Straubel Trail',
    dateOfBirth: new Date('2019-01-01'),
  },
  {
    name: 'Olav Mibourne',
    sex: 'Male',
    email: 'omibourne29@paginegialle.it',
    placeOfBirth: '429 Claremont Circle',
    dateOfBirth: new Date('2015-02-19'),
  },
  {
    name: 'Melinde Salleir',
    sex: 'Female',
    email: 'msalleir2a@geocities.jp',
    placeOfBirth: '7 Loeprich Hill',
    dateOfBirth: new Date('1963-07-27'),
  },
  {
    name: 'Sybila Barge',
    sex: 'Bigender',
    email: 'sbarge2b@weebly.com',
    placeOfBirth: '0806 Heath Place',
    dateOfBirth: new Date('2006-01-22'),
  },
  {
    name: 'Dulcea Kemster',
    sex: 'Female',
    email: 'dkemster2c@dedecms.com',
    placeOfBirth: '0881 Waxwing Circle',
    dateOfBirth: new Date('1995-07-06'),
  },
  {
    name: 'Philippe Comrie',
    sex: 'Female',
    email: 'pcomrie2d@twitter.com',
    placeOfBirth: '3 Colorado Circle',
    dateOfBirth: new Date('2004-09-23'),
  },
  {
    name: 'Dalenna Klimentyonok',
    sex: 'Female',
    email: 'dklimentyonok2e@google.pl',
    placeOfBirth: '10885 Florence Avenue',
    dateOfBirth: new Date('2003-03-24'),
  },
  {
    name: 'Demetri Westmancoat',
    sex: 'Male',
    email: 'dwestmancoat2f@house.gov',
    placeOfBirth: '3 Rigney Trail',
    dateOfBirth: new Date('1963-11-27'),
  },
  {
    name: 'Claiborne Cowe',
    sex: 'Male',
    email: 'ccowe2g@reverbnation.com',
    placeOfBirth: '247 Westerfield Alley',
    dateOfBirth: new Date('2013-12-18'),
  },
  {
    name: 'Josselyn Tewelson',
    sex: 'Female',
    email: 'jtewelson2h@usgs.gov',
    placeOfBirth: '060 Cambridge Point',
    dateOfBirth: new Date('1974-11-11'),
  },
  {
    name: 'Homerus Grabb',
    sex: 'Male',
    email: 'hgrabb2i@privacy.gov.au',
    placeOfBirth: '59335 Merry Way',
    dateOfBirth: new Date('1971-06-13'),
  },
  {
    name: 'Lorie Wetherick',
    sex: 'Female',
    email: 'lwetherick2j@networkadvertising.org',
    placeOfBirth: '0884 Golf Course Terrace',
    dateOfBirth: new Date('1957-05-05'),
  },
  {
    name: 'Rey Cosh',
    sex: 'Male',
    email: 'rcosh2k@comcast.net',
    placeOfBirth: '38194 Pearson Point',
    dateOfBirth: new Date('2011-04-29'),
  },
  {
    name: 'Renae Scane',
    sex: 'Female',
    email: 'rscane2l@hhs.gov',
    placeOfBirth: '735 Sutherland Point',
    dateOfBirth: new Date('1957-02-22'),
  },
  {
    name: 'Moss Honsch',
    sex: 'Male',
    email: 'mhonsch2m@multiply.com',
    placeOfBirth: '04 Ridgeway Lane',
    dateOfBirth: new Date('1983-08-06'),
  },
  {
    name: 'Lydie Rafe',
    sex: 'Male',
    email: 'lrafe2n@alibaba.com',
    placeOfBirth: '88916 Merchant Point',
    dateOfBirth: new Date('2002-07-20'),
  },
  {
    name: 'Rhianna Putman',
    sex: 'Female',
    email: 'rputman2o@a8.net',
    placeOfBirth: '1310 Steensland Avenue',
    dateOfBirth: new Date('1976-01-09'),
  },
  {
    name: 'Pebrook Beccero',
    sex: 'Male',
    email: 'pbeccero2p@bbc.co.uk',
    placeOfBirth: '2 Maywood Road',
    dateOfBirth: new Date('2009-06-06'),
  },
  {
    name: 'Kanya Foskett',
    sex: 'Female',
    email: 'kfoskett2q@wp.com',
    placeOfBirth: '1 Fisk Trail',
    dateOfBirth: new Date('1963-02-20'),
  },
  {
    name: 'Mark Lambourne',
    sex: 'Male',
    email: 'mlambourne2r@ifeng.com',
    placeOfBirth: '29216 Vernon Drive',
    dateOfBirth: new Date('1995-03-02'),
  },
];

export const studyGroups: StudyGroupInput[] = [
  {
    leader: 'Arvin Terlinden',
    name: 'Biodex',
    subject: 'sed interdum venenatis turpis enim blandit mi in porttitor pede',
    time: '9:01 AM',
  },
  {
    leader: 'Gretal Rafferty',
    name: 'Veribet',
    subject:
      'orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi',
    time: '5:38 PM',
  },
  {
    leader: 'Sharon Ferandez',
    name: 'Stringtough',
    subject:
      'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor',
    time: '11:16 AM',
  },
  {
    leader: 'Tatiana Thredder',
    name: 'Transcof',
    subject:
      'tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at',
    time: '2:34 PM',
  },
  {
    leader: 'Teddie Bridal',
    name: 'Trippledex',
    subject:
      'augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit',
    time: '7:04 PM',
  },
  {
    leader: 'Lorene Pawlicki',
    name: 'Zaam-Dox',
    subject:
      'aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo',
    time: '3:36 PM',
  },
  {
    leader: 'Aurore Kristiansen',
    name: 'Zathin',
    subject:
      'etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam',
    time: '6:11 PM',
  },
  {
    leader: 'Laverna Simms',
    name: 'Flowdesk',
    subject:
      'elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis',
    time: '1:31 PM',
  },
];

export const enrollments: EnrollmentInput[] = [
  {
    studyGroupId: 2,
    studentId: 49,
  },
  {
    studyGroupId: 2,
    studentId: 2,
  },
  {
    studyGroupId: 3,
    studentId: 40,
  },
  {
    studyGroupId: 7,
    studentId: 3,
  },
  {
    studyGroupId: 4,
    studentId: 8,
  },
  {
    studyGroupId: 8,
    studentId: 29,
  },
  {
    studyGroupId: 2,
    studentId: 3,
  },
  {
    studyGroupId: 4,
    studentId: 10,
  },
  {
    studyGroupId: 1,
    studentId: 39,
  },
  {
    studyGroupId: 3,
    studentId: 12,
  },
  {
    studyGroupId: 5,
    studentId: 42,
  },
  {
    studyGroupId: 1,
    studentId: 26,
  },
  {
    studyGroupId: 6,
    studentId: 3,
  },
  {
    studyGroupId: 1,
    studentId: 3,
  },
  {
    studyGroupId: 2,
    studentId: 43,
  },
  {
    studyGroupId: 5,
    studentId: 2,
  },
  {
    studyGroupId: 4,
    studentId: 19,
  },
  {
    studyGroupId: 2,
    studentId: 4,
  },
  {
    studyGroupId: 7,
    studentId: 6,
  },
  {
    studyGroupId: 3,
    studentId: 44,
  },
  {
    studyGroupId: 5,
    studentId: 12,
  },
  {
    studyGroupId: 8,
    studentId: 21,
  },
  {
    studyGroupId: 6,
    studentId: 35,
  },
  {
    studyGroupId: 7,
    studentId: 14,
  },
  {
    studyGroupId: 6,
    studentId: 10,
  },
  {
    studyGroupId: 4,
    studentId: 9,
  },
];
