export const ADD_STUDY_GROUPS = 'ADD_STUDY_GROUPS';
export const ADD_STUDY_GROUP = 'ADD_STUDY_GROUP';
export const UPDATE_STUDY_GROUP = 'UPDATE_STUDY_GROUP';
export const DELETE_STUDY_GROUP = ' DELETE_STUDY_GROUP';